/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.util.Date;
import javax.swing.*;

/**
 *
 * @author nanua
 */
public class CashWithdrawl extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form CashWithdrawl
     */
    public CashWithdrawl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    JButton next1,exit2;
    JTextField text1;
    String number;
    Date d1=new Date();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(10, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img2.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));
        JLabel text =new JLabel("Enter Amount you want to Withdraw:");
        text.setFont(new Font("System",Font.BOLD,24));
        text.setForeground(Color.WHITE);
        text.setBounds(235,310,450,30);
        img2.add(text);
        text1 =new JTextField();
        text1.setFont(new Font("System",Font.BOLD,24));
        text1.setBackground(Color.WHITE);
        text1.setForeground(Color.BLACK);
        text1.setBounds(235,345,150,30);
        img2.add(text1);

        next1 =new JButton("Next");
        next1.setBounds(195,515,125,35);
        next1.addActionListener(this);
        img2.add(next1);
        exit2 =new JButton("Exit");
        exit2.setBounds(565,515,125,35);
        exit2.addActionListener(this);
        img2.add(exit2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    void _withdraw() {
        number = text1.getText();
        int value;
        try {
            value = Integer.parseInt(number.trim());
            if (value <= 0) {
                JOptionPane.showMessageDialog(this, "Please enter a positive amount");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number");
            return;
        }

        String d12 = "" + d1;
        try {
            int current_money = 0;
            connec co = new connec();
            Connection con = co.c;
            // Get the latest current balance
            String query1 = "SELECT current FROM balance";
            PreparedStatement pst1 = con.prepareStatement(query1);
            ResultSet rs1 = pst1.executeQuery();
            if (rs1.next()) {
                current_money = rs1.getInt("current");
            }

            if (current_money < value || current_money <= 0) {
                JOptionPane.showMessageDialog(this, "You have not sufficient amount!!");
                return;
            }

            current_money -= value;

            String query = "INSERT INTO balance (current, type, deposit, withdraw, date) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement pst2 = con.prepareStatement(query);
            pst2.setInt(1, current_money);
            pst2.setString(2, "Withdraw");
            pst2.setInt(3, 0); // deposit is 0 for withdraw
            pst2.setInt(4, value);
            pst2.setString(5, d12);

            int i = pst2.executeUpdate();
            if (i > 0) {
                JOptionPane.showMessageDialog(this, "Your money Rs." + value + "\n is withdrawn successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Error occurred during withdrawal");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit2){
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }else if(ae.getSource()==next1){  
                if(((text1.getText())==null)||((text1.getText())=="")){
                    JOptionPane.showMessageDialog(this,"Please enter money"+"\n you wan to withdraw");
                }
                else if(text1.getText()!=null||text1.getText()!=""){
                    _withdraw();
                }
            }
        }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashWithdrawl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           // End of variables declaration                                                                                                                                                                                                                                              
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashWithdrawl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
