/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanua
 */
public class Mini_Statement extends javax.swing.JFrame {

    /**
     * Creates new form Mini_Statement
     */
    public Mini_Statement() {
        initComponents();
        showstate();
    }
    DefaultTableModel model;
    JTable jTable1 = new JTable();
    JScrollPane jScrollPane1 = new JScrollPane();
    int current_set;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel5 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        _total = new javax.swing.JLabel();
        cardno11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Exit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 690, 120, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Mini Statement :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 390, 50));

        _total.setBackground(new java.awt.Color(255, 255, 255));
        _total.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        _total.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 620, 130, 40));

        cardno11.setBackground(new java.awt.Color(255, 255, 255));
        cardno11.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        cardno11.setForeground(new java.awt.Color(0, 0, 0));
        cardno11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cardno11.setText("Your current amount  is :=>");
        jPanel5.add(cardno11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 330, 40));

        jTable2.setBackground(new java.awt.Color(255, 255, 255));
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 690, 510));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 690, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Transaction t2=new Transaction();
        t2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed
    
    void showstate() {
        try {
            Connection con;
            connec co = new connec();
            con = co.c;
            String sql3 = "SELECT * FROM balance";
            PreparedStatement pst3 = con.prepareStatement(sql3);
            ResultSet rs3 = pst3.executeQuery();

            // Set up table model with columns
            DefaultTableModel model = new DefaultTableModel(
                new String[] { "Date","Transaction", "Deposit", "Withdraw","Total" }, 0
            );
            while (rs3.next()) {
                
                Object[] row = {
                    rs3.getString("date"),
                    rs3.getString("type"),
                    rs3.getInt("deposit"),
                    rs3.getInt("withdraw"),
                    current_set=rs3.getInt("current")
                };
                model.addRow(row);
            }
            String set_total=""+current_set;
            _total.setText(set_total);
            jTable2.setModel(model); // Use jTable2, which is shown in GUI
            jTable2.setRowHeight(25);
            jTable2.setRowMargin(5);
            jTable2.setShowGrid(true);
            jTable2.setColumnSelectionAllowed(true);
            jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mini_Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mini_Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mini_Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mini_Statement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mini_Statement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _total;
    private javax.swing.JLabel cardno11;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
