package com.example.simplebankingsystem;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;


/**
 *
 * @author nanua
 */
public class Pinenter2 extends javax.swing.JFrame implements ActionListener{
    JButton next1,exit2;
    JTextField text15;
    String number;
    int value;
    /**
     * Creates new form Pinenter2
     */
    public Pinenter2() {
        initComponents();
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img95 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        img95.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img95)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img95, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JLabel text =new JLabel("Please enter PIN");
        text.setFont(new Font("System",Font.BOLD,24));
        text.setForeground(Color.WHITE);
        text.setBounds(235,310,450,30);
        img95.add(text);
        text15 =new JTextField();
        text15.setFont(new Font("System",Font.BOLD,24));
        text15.setBackground(Color.WHITE);
        text15.setForeground(Color.BLACK);
        text15.setBounds(235,345,150,30);
        img95.add(text15);

        next1 =new JButton("Next");
        next1.setBounds(195,515,125,35);
        next1.addActionListener(this);
        img95.add(next1);
        exit2 =new JButton("Exit");
        exit2.setBounds(565,515,125,35);
        exit2.addActionListener(this);
        img95.add(exit2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    void validate(int PIN){
    boolean found = false;
    try {
        connec co = new connec();
        String query1 = "select * from signupaccount";
        PreparedStatement pst1 = co.c.prepareStatement(query1);
        ResultSet rs1 = pst1.executeQuery();
        while(rs1.next()) {
            int pin = rs1.getInt("pin"); 
            if(pin == PIN){
                found = true;
                PinChange cw1 = new PinChange();
                cw1.setVisible(true);
                this.dispose();
                break;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Please enter correct PIN");
        }
    } catch(Exception e){
        e.printStackTrace();
    }
}

public void actionPerformed(ActionEvent ae){
    if(ae.getSource() == exit2){
        Transaction t1 = new Transaction();
        t1.setVisible(true);
        this.dispose();
    } else if(ae.getSource() == next1){  
        String pinText = text15.getText();
        if (pinText == null || pinText.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter correct PIN");
            return;
        }
        try {
            int enteredPin = Integer.parseInt(pinText.trim());
            validate(enteredPin);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "PIN must be a number");
        }
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinenter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinenter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinenter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinenter2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinenter2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
