/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.simplebankingsystem;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;

/**
 *
 * @author nanua
 */
public class Pinenter1 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Pinenter1
     */
    public Pinenter1() {
        initComponents();
    }
    JButton next11,exit12;
    JTextField text11;
    String number;
    int value;
    void validate(int PIN){
    boolean found = false;
    try {
        connec co = new connec();
        String query1 = "select * from signupaccount";
        PreparedStatement pst1 = co.c.prepareStatement(query1);
        ResultSet rs1 = pst1.executeQuery();
        while(rs1.next()) {
            int pin = rs1.getInt("pin"); 
            if(pin == PIN){
                found = true;
                FastCash cw1 = new FastCash();
                cw1.setVisible(true);
                this.dispose();
                break;
            }
        }
        if (!found) {
            JOptionPane.showMessageDialog(this, "Please enter correct PIN");
        }
    } catch(Exception e){
        System.out.print(e);
    }
}
    public void actionPerformed(ActionEvent ae){
            if(ae.getSource()==exit12){
                Transaction t1=new Transaction();
                t1.setVisible(true);
                this.dispose();
            }else if(ae.getSource()==next11){  
               
                if(((text11.getText())==null)||((text11.getText())=="")){
                    JOptionPane.showMessageDialog(this,"Please enter correct PIN");
                }
                else if(text11.getText()!=null||text11.getText()!=""){
                    String textpin=text11.getText();
                    int text12=Integer.parseInt(textpin);
                    validate(text12);
                }
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel img22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        img22.setIcon(new javax.swing.ImageIcon("C:\\Users\\nanua\\OneDrive\\Desktop\\PROJECT\\Simplebankingsystem\\src\\main\\java\\com\\example\\simplebankingsystem\\atmimage5.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img22)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(img22, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        JLabel text5 =new JLabel("Please enter PIN");
        text5.setFont(new Font("System",Font.BOLD,24));
        text5.setForeground(Color.WHITE);
        text5.setBounds(235,310,450,30);
        img22.add(text5);
        text11 =new JTextField();
        text11.setFont(new Font("System",Font.BOLD,24));
        text11.setBackground(Color.WHITE);
        text11.setForeground(Color.BLACK);
        text11.setBounds(235,345,150,30);
        img22.add(text11);

        next11 =new JButton("Next");
        next11.setBounds(195,515,125,35);
        next11.addActionListener(this);
        img22.add(next11);
        exit12 =new JButton("Exit");
        exit12.setBounds(565,515,125,35);
        exit12.addActionListener(this);
        img22.add(exit12);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pinenter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pinenter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pinenter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pinenter1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pinenter1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
